#!/bin/sh
# runit/2 runs all long-running services

exec > >(logger -t runsvdir) 2>&1

# Link in the startup services
mkdir -p var/service
ln -sf /etc/service/syslog /var/service/
ln -sf /etc/service/cron /var/service/
ln -sf /etc/service/dhcp /var/service/
ln -sf /etc/service/ntp /var/service/
ln -sf /etc/service/ssh /var/service/

# Continuously startup and supervise everything in /var/service
exec runsvdir /var/service
