#!/bin/sh
# Setup long-running services

ln -s /etc/service/syslog /var/service/
ln -s /etc/service/cron   /var/service/
ln -s /etc/service/dhcp   /var/service/
ln -s /etc/service/ntp    /var/service/
ln -s /etc/service/ssh    /var/service/

# Continuously startup and supervise everything in /var/service
exec > >(logger -t runsvdir) 2>&1
exec runsvdir /var/service
