#!/bin/sh

. $ZIGROOT/clang-cross/utils.sh

ARGS="$@"
NEWARGS=$(rewrite_flags $ARGS)

zig cc \
  --target=aarch64-linux-musl \
  -fuse-ld="lld-16" \
  --ld-path=$ZIGROOT/clang-cross/clang-cross-lld \
  $NEWARGS
